STATE_HEARTBEAT = 0
STATE_TEMPERATURE = 1
STATE_AUDIO = 2
STATE_CAMERA = 3
STATE_STEP = 4
STATE_TEXT_2_SPEECH = 5
STATE_ACTIVITY_TRIGGER = 6
STATE_ACTIVITY_TRIGGER_IMAGE = 7
STATE_ACTIVITY_TRIGGER_AUDIO = 8


STATE_ENV_ACTIVITY_CMD_TAKING_IMAGE = 10
STATE_ENV_ACTIVITY_CMD_TAKING_AUDIO = 11 
STATE_ENV_ACTIVITY_CMD_TAKING_MOTION = 12
STATE_ENV_ACTIVITY_CMD_TAKING_FUSION = 13

# STATE_MEDICATION_ACTIVITY_CMD_TAKING_IMAGE = 10
# STATE_MEDICATION_ACTIVITY_CMD_PLAY_AUDIO = 11

STATE_ADL_ACTIVITY_WMU_AUDIO = 15
STATE_ADL_ACTIVITY_WMU_IMAGE = 16
STATE_ADL_ACTIVITY_WMU_MOTION = 17

WMU_MOTION_FILE_NOTIFICATION_FILE = 'notice.txt'
WMU_AUDIO_FILE_NOTIFICATION_FILE = 'notice.txt'
WMU_IMAGE_FILE_NOTIFICATION_FILE = 'notice.txt'


MOTION_FILE_SAVED_FOLDER = 'E:\ASCCDATA\MOTION'
AUDIO_FILE_SAVED_FOLDER = 'E:\ASCCDATA\audio'
IMAGE_FILE_SAVED_FOLDER = 'E:\ASCCDATA\image'
IMAGE_FILE_SAVED_FOLDER = 'E:\ASCCDATA\image'


DATE_TIME_FORMAT = '%Y%m%d%H%M%S'


# WMU
WMU_IPRECEIVE = "192.168.0.127" 
# WMU_IPSEND = "10.227.99.196"
WMU_IPSEND = '192.168.0.105'
#WMU_IPRECEIVE = "192.168.1.131"
#WMU_IPSEND = "192.168.1.126"
WMU_RECEIVE_PORT = 8080 # WMU server
WMU_SEND_PORT = 59000 # robot server


ROBOT_IP = WMU_IPSEND 
ROBOT_PORT = WMU_SEND_PORT # robot server


